# matrix multiplication

In [1]:
import numpy as np

In [2]:
bias = np.array([[1, 1, 1,]])
bias.T

array([[1],
       [1],
       [1]])

In [3]:
sample_weights = np.random.randn(2, 3)
sample_weights

array([[-0.05761746, -0.01760135,  2.17468788],
       [-0.68808116,  0.83059226,  0.32592817]])

In [4]:
np.arange(2)

array([0, 1])

In [5]:
input = np.arange(2)
input = input.reshape(1, -1)
input

array([[0, 1]])

In [6]:
input @ sample_weights

array([[-0.68808116,  0.83059226,  0.32592817]])

In [7]:
input @ sample_weights + bias

array([[0.31191884, 1.83059226, 1.32592817]])

In [8]:
sample_weights.T @ input.T + bias.T

array([[0.31191884],
       [1.83059226],
       [1.32592817]])

# PyTroch

In [9]:
import torch
import torch.nn as nn

# Create a simple linear layer
linear = nn.Linear(3, 2)  # Input features = 3, Output features = 2

# Print the initial weight and bias values
print("Initial Weights:\n", linear.weight)
print("Initial Biases:\n", linear.bias)


Initial Weights:
 Parameter containing:
tensor([[ 0.3034, -0.5266, -0.4876],
        [ 0.1011, -0.3723, -0.3080]], requires_grad=True)
Initial Biases:
 Parameter containing:
tensor([ 0.4791, -0.4978], requires_grad=True)


In [10]:
print(torch.all(linear.bias == 0))  # Should print True

tensor(False)


In [11]:
np.full(10, 0.01)

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])

In [12]:
input_size = 2
output_size = 3

np.random.normal(0, np.sqrt(2/input_size), (input_size, output_size))

array([[-0.09589778,  0.29144762, -0.407925  ],
       [-0.27242556,  0.50827066,  0.60349937]])

In [17]:
(np.array([5, 4, 3,]) - np.array([1, 1, 1,]))**2

array([16,  9,  4])

In [18]:
np.mean((np.array([5, 4, 3,]) - np.array([1, 1, 1,]))**2)

9.666666666666666

In [24]:
sum(np.array([5, 4, 3,]) - np.array([1, 1, 1,]))

9