In [ ]:
import numpy as np

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
bias = np.array([[1, 1, 1,]])
bias.T

array([[1],
       [1],
       [1]])

In [ ]:
sample_weights = np.random.randn(3, 2)  # output, input dimensions
sample_weights

array([[ 1.03756777, -0.70744718],
       [ 0.57074401, -0.99834887],
       [-1.75260382,  0.90337511]])

In [48]:
input = np.arange(2)
input = input.reshape(1, -1)
input

array([[0, 1]])

In [49]:
input @ sample_weights

array([[-0.73012674,  0.67591836, -0.92060675]])

In [63]:
sample_weights.T @ input.T + bias.T

array([[0.26987326],
       [1.67591836],
       [0.07939325]])