# matrix multiplication

In [1]:
import numpy as np

In [2]:
bias = np.array([[1, 1, 1,]])
bias.T

array([[1],
       [1],
       [1]])

In [7]:
sample_weights = np.random.randn(2, 3)
sample_weights

array([[ 1.30816113, -1.24459131, -1.16548861],
       [ 0.1095687 , -0.28227441, -0.26477888]])

In [8]:
np.arange(2)

array([0, 1])

In [9]:
input = np.arange(2)
input = input.reshape(1, -1)
input

array([[0, 1]])

In [10]:
input @ sample_weights

array([[ 0.1095687 , -0.28227441, -0.26477888]])

In [12]:
input @ sample_weights + bias

array([[1.1095687 , 0.71772559, 0.73522112]])

In [13]:
sample_weights.T @ input.T + bias.T

array([[1.1095687 ],
       [0.71772559],
       [0.73522112]])

# PyTroch

In [14]:
import torch
import torch.nn as nn

# Create a simple linear layer
linear = nn.Linear(3, 2)  # Input features = 3, Output features = 2

# Print the initial weight and bias values
print("Initial Weights:\n", linear.weight)
print("Initial Biases:\n", linear.bias)


Initial Weights:
 Parameter containing:
tensor([[-0.1325,  0.1691,  0.2635],
        [-0.2317, -0.2511,  0.0509]], requires_grad=True)
Initial Biases:
 Parameter containing:
tensor([-0.5305, -0.1427], requires_grad=True)


In [15]:
print(torch.all(linear.bias == 0))  # Should print True

tensor(False)


In [16]:
np.full(10, 0.01)

array([0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01])

In [17]:
input_size = 2
output_size = 3

np.random.normal(0, np.sqrt(2/input_size), (input_size, output_size))

array([[ 0.84749578, -0.16548117, -1.31966373],
       [ 1.68251871, -0.17947308,  0.54334135]])